const BusinessPartnerDTO = {
	addressNumber: "",
	businessPartnerType: null,
	createdDate: new Date(),
	createdName: "",
	createdOrgName: "",
	createdRankName: "",
	creater: null,
	customer: "",
	description: "",
	eMailAddress1: "",
	eMailAddress2: "",
	id: null,
	isActive: true,
	isDelete: false,
	isSyncFromSAP: false,
	maChuoi: "",
	modifiedDate: new Date(),
	modifiedName: "",
	modifier: null,
	name: "",
	street: "",
	telephone: "",
	tenChuoi: "",
	timeSync: new Date(),
	vatTegistrationNo: "",
};
export default BusinessPartnerDTO;
