const CargoServiceDto = {
	cargoCode: "",
	createdDate: new Date(),
	createdName: "",
	createdOrgName: "",
	createdRankName: "",
	description: "",
	don_gia_chuan: null,
	don_gia_cung_ung_phe_duyet: "",
	don_gia_ha_noi: null,
	don_gia_ha_noi_str: "",
	don_gia_hcm: "",
	don_gia_hcm_str: "",
	don_gia_ncc: null,
	don_vi_tinh: null,
	id: null,
	isActive: true,
	isDelete: false,
	ma_hieu: "",
	modifiedDate: new Date(),
	modifiedName: "",
	ncc_cupd: "",
	nha_cung_cap: "",
	noi_dung_cong_viec: "",
	quy_cach_ky_thuat: "",
	showAll: false,
	so_luong: "",
	stt: null,
	thanh_tien: "",
	thanh_tien_cupd: "",

};
export default CargoServiceDto;