
const CargoMeDto = {
	cargoCode: "",
	createdDate: new Date(),
	createdName: "",
	createdOrgName: "",
	createdRankName: "",
	description: "",
	don_gia_chuan_nhan_cong: null,
	don_gia_chuan_vt_vl: null,
	don_gia_ncc_nhan_cong: null,
	don_gia_ncc_nhan_cong_cupd: null,
	don_gia_ncc_vt_vl: null,
	don_gia_ncc_vl_vt_cupd: null,
	don_gia_nhan_cong: null,
	don_gia_nhan_cong_str: "",
	don_gia_vat_tu_vat_lieu: null,
	don_gia_vat_tu_vat_lieu_str: "",
	don_vi_tinh: "",
	id: "",
	isActive: true,
	isDelete: false,
	ma_hieu: "",
	modifiedDate: new Date(),
	modifiedName: "",
	ncc: "",
	ncc_cupd: "",
	noi_dung_cong_viec: "",
	quy_cach_ky_thuat: "",
	showAll: false,
	so_luong: "",
	stt: null,
	thanh_tien: "",
	thanh_tien_cupd: "",

};
export default CargoMeDto;