const CentralizedDTO = {
	bangSo: null,
	cBLDPnLPheDuyet: "",
	createdDate: new Date(),
	createdName: "",
	createdOrgName: "",
	createdRankName: "",
	dVTSAP: "",
	description: "",
	doDaiShortName: null,
	fullName: "",
	ghiChuKhac: "",
	iDGuiITXuLy: "",
	id: null,
	isActive: true,
	isDelete: false,
	isSyncFromSAP: false,
	level1: "",
	level2: "",
	level3: "",
	level4: "",
	maChungPnL: "",
	modifiedDate: new Date(),
	modifiedName: "",
	ngayTaoMa: "",
	noteKhoaMa: "",
	pICYeuCauTaoMa: "",
	pLSuDung: "",
	shortName: "",
	stt: null,
	tenNhomLevel1: "",
	tenNhomLevel2: "",
	tenNhomLevel3: "",
	tenNhomLevel4: "",
	timeSync: new Date(),

};

export default CentralizedDTO;
