const TransferHandleDTO = {
	attachFileList: "",
	content: "",
	createdDate: new Date(),
	createdName: "",
	createdOrgName: "",
	createdRankName: "",
	creater: null,
	dispatchBook: null,
	dispatchBookCode: "",
	dispatchBookName: "",
	expiredTime: null,
	id: null,
	isActive: true,
	isDelete: true,
	modifiedDate: new Date(),
	modifiedName: "",
	modifier: null,
	order: 0,
	orgCode: "",
	orgName: "",
	organization: null,
	processDate: "",
	receiversHandles: null,
	statusName: "",
	statusTransferHandle: null,
	transfer: null,
	transferAvatar: "",
	transferEmail: "",
	transferName: "",
	stepData: {},
};
export default TransferHandleDTO;
